### ISSUE TITLE
Log record type 19?

### ISSUE THREAD

**Issue by l-k-** [actigraph/GT3X-File-Format#13]
I'm parsing a .gt3x file generated by a MOS2 device, firmware: 1.9.2, and I see records of type 19, which is not listed in https://github.com/actigraph/GT3X-File-Format#log-record-types. 

Is this a new type? Is there any information at all about it?

thank you in advance!

**Comment by blitzxion** [comment]
@l-k- 
We've updated our documentation to reflect the data you found. You can find the information [regarding this type here](https://github.com/actigraph/GT3X-File-Format#internaldiagnostic-log-record-types).

In summary: The .gt3x file may contain additional record types that don't map directly to an expected Log Record type. These unknown types are utilized internally by ActiGraph engineers for diagnostic purposes. Records with these types can be ignored (or skipped over).

If you have any further questions, you can contact us directly at support@theactigraph.com.
