### ISSUE TITLE
Activity records with 1 byte payload?

### ISSUE THREAD

**Issue by l-k-** [actigraph/GT3X-File-Format#15]
I'm parsing a .gt3x file generated by a MOS2 device, firmware: 1.9.2, and I get some Activity records (type 0) that have a payload of only 1 byte. So they can't be parsed as YXZ samples. What are these records? Do they have a meaning? Or is the file got corrupted somehow? The rest of the file parses just fine.

I did try contacting support@theactigraph.com, like you suggested in another issue, but got a reply that this is "outside of the scope of what [they] can support".

Thank you in advance!

**Comment by izmirlig** [comment]
I'm not the author but I've hacked around and written a driver in C that I call through R. I haven't finished documenting the package yet so it is not yet up on CRAN. I can say this however, firmware versions up through 2.5.0 contain just the activity data. Therefore you must be looking at a corrupted portion of the file.



Grant Izmirlian, Ph.D.
Mathematical Statistician
izmirlig@mail.nih.gov



Delivery Address:
9609 Medical Center Dr, RM 5E130<http://<a%20href=https://goo.gl/maps/hazeG59G3P82>>
Rockville MD 20850

Postal Address:
BG 9609 RM 5E130 MSC 9789
9609 Medical Center Dr
Bethesda, MD 20892-9789

 ofc:  240-276-7025
 cell: 240-888-7367
  fax: 240-276-7845

________________________________

**Comment by rdefour19** [comment]
https://github.com/actigraph/GT3X-File-Format/pull/16

**Comment by l-k-** [comment]
Thank you!!
