### ISSUE TITLE
Confusion around ```PARAMETERS Packet - ID 21```

### ISSUE THREAD

**Issue by angerhang** [actigraph/GT3X-File-Format#17]
I have been trying to reimplement the encoding and the decoding function for the floating number for the `parameter` packet, but the examples shown seem to deviate from c# code. Not sure which one is the right one to follow.

For instance, when encoding 30, the documentation gives us `1E 00 00 00 00` whereas the sample encode function yields: 
![Screen Shot 2020-04-20 at 8 41 22 PM](https://user-images.githubusercontent.com/7655454/79792743-54645680-8347-11ea-9665-b1ef4704551c.png)

01 00 0A 00 1E 00 00 00 | SAMPLE_RATE: 30 Hz.

Of course, some of the values in the [reference](https://github.com/actigraph/GT3X-File-Format/blob/master/LogRecords/Parameters.md) match with the sample function but many don't. Is there a mistake in the documentation, if so what we should follow for the decoding for the floating point?

**Comment by angerhang** [comment]
https://github.com/actigraph/GT3X-File-Format/issues/9 is related to this. The encoding and decoding functions do seem correct to me for the floating-point representation. I am afraid that the examples in the table are not all proper.

**Comment by jmaygarden** [comment]
Sample rate is an unsigned integer. It should not be encoded.

The floating-point encoding comes from this  paper: https://www.scribd.com/document/98159712/Simple-Serial-Protocol-SSP

**Comment by angerhang** [comment]
Ah i see. So we will read out different parameters based on the types they've got. Thx!
