### ISSUE TITLE
Does GT3X file log the idle.sleep.mode setting?

### ISSUE THREAD

**Issue by vincentvanhees** [actigraph/GT3X-File-Format#22]
I am correct to conclude that the GT3X file does not log whether idle.sleep.mode was turned on or off?

At the moment I scan the file for timestamp gaps larger than 5 seconds, which I then use as a crude indicator of whether idle.sleep.mode was turned on.

If not, then it would be good if you could add this in future updates of the file format as it would provide a more complete description of the data and it would ease processing the files (knowing how much memory to allocate). Further, it may be good if you could store the number of samples (data points) in a file, which in combination with start-end time would also provide insight into the degree of timegaps.

Thanks

**Comment by angerhang** [comment]
I had experienced similar issues with GT3X especially for firmwares < 2.5.0. I would second @vincentvanhees 's view on this.

**Comment by angerhang** [comment]
Just look up the contributors's current affiliations. It seems that all of them left Actigraph already and no one seems to be maintaining this repository anymore. It would be good to give the community a sense of how would be the new point of contact? @jmaygarden @rdefour19 @jmaygarden @blitzxion

**Comment by vincentvanhees** [comment]
> Just look up the contributors' current affiliations. It seems that all of them left Actigraph already

@m-patterson-wearable recently joint @actigraph => Matt, would you mind forwarding this message to the relevant person within ActiGraph?

I think, it would really help if Actigraph could continue to maintain this repository. There a number of data format variations and it would be great if we could work towards a central code base that can handle all of them. It may even be worth trying to establish a central C++ code library for this to be used as dependency in both Python and R packages.

**Comment by angerhang** [comment]
> 

Sure thing? Can you share a Github link?

**Comment by angerhang** [comment]
> I have an R project in with kernel in plain C for reading in firmware versions 2.5.0 and 3.1.0 if anyone's interested. From: Vincent van Hees ***@***.***> Sent: Monday, June 13, 2022 1:36 PM To: actigraph/GT3X-File-Format ***@***.***> Cc: 

Sure can you share a Github link somewhere?
